// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventoryAPI.Models;

public partial class User
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string LoginName { get; set; }

    public string LoginPassword { get; set; }

    public string UserRole { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }
}